name: Construcción y Publicación de Imagen Docker
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build and tag Docker image
        id: build-image
        env:
          DOCKER_IMAGE_NAME: healthcarer-api
        run: |
          
          IMAGE_TAG=${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
          
          
          echo "Building image with tag: $IMAGE_TAG"
          docker build -t $IMAGE_TAG .
          
          
          DEV_TAG=${{ env.DOCKER_IMAGE_NAME }}:dev
          echo "Tagging image as: $DEV_TAG"
          docker tag $IMAGE_TAG $DEV_TAG

          
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "DEV_TAG=$DEV_TAG" >> $GITHUB_OUTPUT


      - name: Push the images
        env:
          DOCKER_IMAGE_TAGS: ${{ steps.build-image.outputs.IMAGE_TAG }},${{ steps.build-image.outputs.DEV_TAG }}
        run: |
          echo "Pushing images to Docker Hub"
          docker push $DOCKER_IMAGE_TAGS
