name: WorkflowIntegration

on:
  push:
    paths:
      - 'src/**'
      - 'pom.xml'
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3
      - name: Configurar JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'
          cache: 'maven'
      - name: Instalar dependencias de Maven
        run: mvn clean install -DskipTests
      - name: Ejecutar tests de integración
        run: mvn test -Dtest="**/integration/*"
