name: Pruebas unitarias/integración/e2e en pull-requests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3
      - name: Configurar JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'
      - name: Ejecutar tests unitarios
        run: mvn test -Dtest="**/unitary/*"
      - name: Ejecutar tests de integración
        run: mvn test -Dtest="**/integration/*"
      - name: Ejecutar tests de sistema
        run: mvn test -Dtest="**/e2e/*"
        env:
          APP_BASE_URL: http://localhost:8443
