name: WorkflowIntegration

on:
  push:
    paths:
      - src/**
      - pom.xml
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3
      - name: Configurar JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'openjdk'
          java-version: '22'
      - name: Ejecutar tests de integración
        run: mvn test -Dtest="/integration/*"
